info:
  contact: {}
paths:
  /health:
    get:
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: health checker API
  /version:
    get:
      responses:
        "200":
          description: 0.0.1
          schema:
            type: string
      summary: service version API
swagger: "2.0"
