name: CICD

on:
  push:
    branches:
    - master
    paths-ignore:
    - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build
      run: go build -v ./...
    - name: Test
      run: go test -v ./...

  release-docker:
    runs-on: ubuntu-latest
    steps:
      -
       name: Setup Docker Buildx
       uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: borischen0203/litclock-service:latest
    needs: [build]

  release-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "litclock-service" #Must be unique in Heroku
          heroku_email: "borischen0203@gmail.com"
          usedocker: true
    needs: [release-docker]

